version: '3'
services:
  app:
    build:
      args:
        uid: ${UID}
        gid: ${GID}
      context: ./
      dockerfile: Dockerfile
    image: cyje
    container_name: cyje-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cyje
  db:
    image: yobasystems/alpine-mariadb:10.4.15
    container_name: cyje-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - cyje
  cache:
    image: redis:6-alpine
    container_name: cyje-cache
    restart: unless-stopped
    networks:
      - cyje
  web:
    image: nginx:alpine
    container_name: cyje-web
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.conf/nginx:/etc/nginx/conf.d
    networks:
      - cyje
networks:
  cyje:
    driver: bridge